In [1]:
import numpy as np

## 1차원배열

In [11]:
# array
ar = np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [9]:
ar2 = np.array([1.1,2.2,3.3])
ar2

array([1.1, 2.2, 3.3])

In [12]:
# 벡터연산
ar3 = ar2 * 2
ar3

array([2.2, 4.4, 6.6])

In [13]:
ar3 > 4

array([False,  True,  True])

In [15]:
(ar2 >2) & (ar3 > 4)

array([False,  True,  True])

## 2차원배열

In [18]:
arar =np.array([[1,1,1],[1,1,1]])
arar

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
# 행
len(arar)

2

In [21]:
# 열
len(arar[0])

3

## 3차원배열

In [26]:
ararar = np.array([[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]])
ararar

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [27]:
len(ararar), len(ararar[0]) , len(ararar[0][0])

(2, 3, 3)